REM Code Generated by Sidekick is for learning and experimentation purposes only.
@echo off
setlocal EnableExtensions

REM ============================================================
REM Synthetic secret-like values for scanner testing only
REM All values are fake, invalid, and non-functional
REM ============================================================

REM --- Salesforce / CRM-like ---
set SF_USERNAME=svc_pipeline_sync@acme-uat.example.invalid
set SF_PASSWORD=NotARealPassword!2026!SyntheticOnly
set SF_SECURITY_TOKEN=TESTTOKEN9QW8E7R6T5Y4U3I2O1P0
set SF_CLIENT_ID=3MVG9fFAKEEXAMPLE7hLxZ0TESTAPPKEY1234567890ABCDE
set SF_CLIENT_SECRET=FAKE_SF_ClientSecret_x9K2mP7Qv4Rz8Tn1Yw6Bc3Hd
set SF_ACCESS_TOKEN=00Dxx0000001AbC!AQ8AQFakeSalesforceAccessTokenValueForScannerTestingOnly
set SF_REFRESH_TOKEN=5Aep86123FAKERefreshTokenValueOnlyForSecretScannerLab
set SF_SESSION_ID=00Dxx0000001AbC!AR8AQMDSyntheticSessionIdForDetectionTestingOnly
set SFDX_AUTH_URL=force://PlatformCLI::3MVG9fFAKEEXAMPLE7hLxZ0TESTAPPKEY1234567890ABCDE::00Dxx0000001AbC!AQ8AQFakeSalesforceAccessTokenValueForScannerTestingOnly@acme-uat.my.salesforce.com

REM --- AWS-like ---
set AWS_ACCESS_KEY_ID=AKIAFAKE1234TEST5678
set AWS_SECRET_ACCESS_KEY=FAKEAWSSECRETKEY1234567890abcdefghijklmnopqrstuvwxyz
set AWS_SESSION_TOKEN=IQoJb3JpZ2luX2VjEOj__________FAKE_SESSION_TOKEN_FOR_TESTING_ONLY
set AWS_ACCOUNT_ID=123456789012

REM --- Azure-like ---
set AZURE_STORAGE_KEY=FakeAzureStorageKeyBase64LikeValue1234567890ABCDEFG==
set AZURE_CLIENT_ID=11111111-2222-3333-4444-555555555555
set AZURE_CLIENT_SECRET=FakeAzureClientSecret_Value_For_Scanner_Testing_Only
set AZURE_TENANT_ID=aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee
set AZURE_SUBSCRIPTION_ID=99999999-8888-7777-6666-555555555555

REM --- GCP-like ---
set GOOGLE_API_KEY=AIzaSyFAKE_TEST_KEY_1234567890_ABCDEFG
set GCP_PROJECT_ID=acme-synthetic-project
set GCP_CLIENT_EMAIL=svc-acme-test@acme-synthetic-project.iam.gserviceaccount.com
set GCP_PRIVATE_KEY_ID=fakeprivatekeyid1234567890abcdef
set GCP_PRIVATE_KEY=-----BEGIN PRIVATE KEY-----FAKEGCPPRIVATEKEYMATERIALFORTESTINGONLY-----END PRIVATE KEY-----

REM --- Git providers ---
set GITHUB_TOKEN=ghp_FAKE9x2Lm3Np4Qr5St6Uv7Wx8Yz012345678
set GITHUB_FINE_GRAINED=github_pat_FAKE_1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZ
set GITLAB_TOKEN=glpat-FAKE_1234567890abcdefghijklmnop
set BITBUCKET_APP_PASSWORD=BBAPP-FAKE-PASSWORD-123456789

REM --- CI/CD ---
set JENKINS_API_TOKEN=11aa22bb33cc44dd55ee66ff77gg88hh
set CIRCLECI_TOKEN=FAKECIRCLECITOKEN1234567890abcd
set TRAVIS_TOKEN=FAKETRAVISTOKEN1234567890

REM --- Messaging / collaboration ---
set SLACK_BOT_TOKEN=xoxb-111111111111-222222222222-FAKESlackTokenForScannerTesting
set SLACK_SIGNING_SECRET=FakeSlackSigningSecret1234567890abcdef
set DISCORD_BOT_TOKEN=FAKE.DISCORD.BOT.TOKEN_1234567890
set TEAMS_WEBHOOK=FakeTeamsWebhookSecretValue123456

REM --- Payment / communications ---
set STRIPE_SECRET_KEY=sk_test_FAKE51NmJkPExampleSecretScannerOnly
set STRIPE_WEBHOOK_SECRET=whsec_FAKE_SalesforceWebhookSecret_123456789abcdef
set TWILIO_ACCOUNT_SID=ACFAKE1234567890abcdef1234567890ab
set TWILIO_AUTH_TOKEN=faketwilioauthtoken1234567890abcd
set SENDGRID_API_KEY=SG.FAKE_PART_ONE.FAKE_PART_TWO_FOR_TESTING_ONLY
set MAILGUN_API_KEY=key-FAKEMAILGUN1234567890abcdef

REM --- Identity / OAuth / JWT ---
set OAUTH_CLIENT_ID=fake-oauth-client-id-123456.apps.example.invalid
set OAUTH_CLIENT_SECRET=FakeOAuthClientSecret_abcdefghijklmnopqrstuvwxyz
set OKTA_API_TOKEN=00FAKEOktaApiTokenValue1234567890abcdef
set JWT_BEARER=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.FAKE_PAYLOAD_FOR_SCANNER_TESTING.FAKE_SIGNATURE_ONLY
set BASIC_AUTH_HEADER=Basic c3ZjX3BpcGVsaW5lX3N5bmM6Tm90QVJlYWxQYXNzd29yZCEyMDI2
set BEARER_HEADER=Bearer eyJraWQiOiJGQUtFIiwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYifQ.FAKE.PAYLOAD

REM --- Databases / connection strings ---
set DB_USERNAME=svc_app_user
set DB_PASSWORD=FakeDbPassword!2026!ScannerOnly
set JDBC_URL=jdbc:postgresql://db.acme.internal:5432/appdb?user=svc_app_user^&password=FakeDbPassword!2026!ScannerOnly
set MONGO_URI=mongodb://svc_app_user:FakeMongoPass123@mongo1.example.invalid:27017/appdb
set REDIS_URL=redis://:FakeRedisPass123@redis.example.invalid:6379/0
set SNOWFLAKE_PASSWORD=FakeSnowflakePassword!ScannerOnly

REM --- Dev tooling / package registries ---
set NPM_TOKEN=npm_FAKE_1234567890abcdefghijklmnopqrstuvwxyz
set PYPI_TOKEN=pypi-AgENdGVzdC5weXBpLm9yZwIkFAKEPYPI1234567890abcdef
set DOCKERHUB_PASSWORD=FakeDockerHubPassword_12345
set ARTIFACTORY_API_KEY=AKCFAKEARTIFACTORY1234567890
set SONATYPE_TOKEN=FakeSonatypeToken_1234567890abcdef

REM --- Monitoring / observability ---
set DATADOG_API_KEY=fakedatadogapikey1234567890abcdef
set NEWRELIC_LICENSE_KEY=NRII-FAKE-1234567890abcdef1234567890abcd
set SPLUNK_HEC_TOKEN=12345678-1234-1234-1234-1234567890ab
set SENTRY_AUTH_TOKEN=sntrys_FAKE_AUTH_TOKEN_1234567890abcdefghijkl

REM --- Incident / support ---
set PAGERDUTY_API_KEY=FAKEPAGERDUTYAPIKEY1234567890
set ZENDESK_API_TOKEN=fakezendeskapitoken1234567890abcdef

REM --- Encryption / signing / webhook-like ---
set WEBHOOK_SIGNING_SECRET=whsec_FAKE_WEBHOOK_SIGNING_SECRET_987654321abcdef
set HMAC_SECRET=FakeHmacSharedSecret_ABCDEFGHIJKLMNOPQRSTUVWXYZ
set ENCRYPTION_KEY=FakeEncryptionKey_32Chars_Long_1234
set RSA_PRIVATE_KEY_PASSWORD=FakeRsaKeyPassphrase_ForScannerTesting

REM --- SSH / PEM / cert-like written to files ---
(
  echo -----BEGIN PRIVATE KEY-----
  echo FAKE_PRIVATE_KEY_MATERIAL_FOR_SECRET_SCANNER_TESTING_ONLY
  echo ZXhhbXBsZVN5bnRoZXRpY1ByaXZhdGVLZXlGb3JTZWNyZXRTY2FubmVyVGVzdA==
  echo -----END PRIVATE KEY-----
) > fake_private_key.pem

(
  echo -----BEGIN OPENSSH PRIVATE KEY-----
  echo FAKE_OPENSSH_PRIVATE_KEY_FOR_SCANNER_TESTING_ONLY
  echo b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAlwAAAAdz
  echo -----END OPENSSH PRIVATE KEY-----
) > fake_id_rsa

(
  echo -----BEGIN CERTIFICATE-----
  echo FAKE_CERTIFICATE_DATA_FOR_TESTING_ONLY
  echo TUlJQkZBS0VDRVJUSUZJQ0FURURBVEExMjM0NTY3ODkw
  echo -----END CERTIFICATE-----
) > fake_cert.crt

REM --- Kubernetes / config-like ---
set KUBE_TOKEN=eyJhbGciOiJSUzI1NiIsImtpZCI6IkZBS0UifQ.FAKE_K8S_PAYLOAD.FAKE_K8S_SIGNATURE
set KUBECONFIG_USER=svc-k8s-test
set KUBECONFIG_PASSWORD=FakeKubeConfigPassword123!

REM --- Misc scanner bait ---
set PRIVATE_KEY=-----BEGIN PRIVATE KEY-----FAKEINLINEPRIVATEKEY-----END PRIVATE KEY-----
set API_KEY=FAKE_GENERIC_API_KEY_1234567890
set SECRET_KEY=FAKE_GENERIC_SECRET_KEY_abcdefghijklmnopqrstuvwxyz
set ACCESS_TOKEN=FAKE_GENERIC_ACCESS_TOKEN_1234567890
set REFRESH_TOKEN=FAKE_GENERIC_REFRESH_TOKEN_abcdefghijklmnopqrstuvwxyz
set CLIENT_SECRET=FAKE_GENERIC_CLIENT_SECRET_1234567890abcdef
set PASSWORD=FakeGenericPassword!123
set TOKEN=FAKE_GENERIC_TOKEN_XYZ_1234567890
set LICENSE_KEY=FAKE-LICENSE-KEY-1234-5678-ABCD-EFGH
set SIGNING_KEY=FAKE_SIGNING_KEY_ABCDEFGHIJKLMNOPQRSTUVWXYZ

echo Synthetic secret test file created.
echo PEM-like files written: fake_private_key.pem, fake_id_rsa, fake_cert.crt

endlocal
